CC = gcc
DEBUG = -Wall -g

.PHONY: clean

objs = main.o tileset.o map.o draw.o sprite.o text.o inv.o node.o tools.o

all: nate

nate: $(objs)
	$(CC) $(DEBUG) $(objs) -o $@ -lalleg

main.o: main.c main.h
	$(CC) $(DEBUG) -c $< -o $@
	
tileset.o: tileset.c tileset.h
	$(CC) $(DEBUG) -c $< -o $@

map.o: map.c map.h
	$(CC) $(DEBUG) -c $< -o $@
	
draw.o: draw.c draw.h
	$(CC) $(DEBUG) -c $< -o $@
	
sprite.o: sprite.c sprite.h
	$(CC) $(DEBUG) -c $< -o $@
	
text.o: text.c text.h
	$(CC) $(DEBUG) -c $< -o $@
	
inv.o: inv.c inv.h
	$(CC) $(DEBUG) -c $< -o $@
	
node.o: node.c node.h
	$(CC) $(DEBUG) -c $< -o $@
	
tools.o: tools.c tools.h
	$(CC) $(DEBUG) -c $< -o $@

clean:
	del /S *.o
	del nate.exe
