CC = wcc386
LD = wlink
CFLAGS = -w1 -3s -s
bin = nate.exe

obj = main.obj tileset.obj map.obj draw.obj sprite.obj text.obj inv.obj vend.obj temp.obj elev.obj fight.obj grid.obj node.obj tools.obj

	
$(bin): $(obj)
	$(LD) name $@ file *.obj LIBRARY alleg
	
.c.obj:
	$(CC) -fo=$@ $(CFLAGS) $<

clean: .symbolic
	del *.obj
	del $(bin)
	del *.err
