<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.4" name="nateroom" tilewidth="20" tileheight="20" tilecount="160" columns="16">
 <image source="../NATE.bmp" width="320" height="200"/>
 <tile id="0" type="SOLID"/>
 <tile id="1" type="SOLID"/>
 <tile id="2" type="SOLID"/>
 <tile id="16" type="SOLID"/>
 <tile id="17" type="SOLID"/>
 <tile id="18" type="SOLID"/>
 <tile id="32" type="SOLID"/>
 <tile id="33" type="SOLID"/>
 <tile id="34" type="SOLID"/>
 <tile id="48" type="SOLID"/>
 <tile id="49" type="SOLID"/>
 <tile id="50" type="SOLID"/>
 <tile id="52" type="SOLID"/>
 <tile id="53" type="SOLID"/>
 <tile id="54" type="SOLID"/>
 <tile id="55" type="SOLID"/>
 <tile id="56" type="SOLID"/>
 <tile id="57" type="SOLID"/>
 <tile id="58" type="SOLID"/>
 <tile id="64" type="SOLID"/>
 <tile id="65" type="SOLID"/>
 <tile id="66" type="SOLID"/>
 <tile id="67" type="SOLID"/>
 <tile id="75" type="SOLID"/>
 <tile id="80" type="SOLID"/>
 <tile id="81" type="SOLID"/>
 <tile id="82" type="SOLID"/>
 <tile id="83" type="SOLID"/>
 <tile id="84" type="SOLID"/>
 <tile id="90" type="SOLID"/>
 <tile id="96" type="SOLID"/>
 <tile id="97" type="SOLID"/>
 <tile id="98" type="SOLID"/>
 <tile id="106" type="SOLID"/>
 <tile id="112" type="SOLID"/>
 <tile id="113" type="SOLID"/>
 <tile id="114" type="SOLID"/>
 <tile id="122" type="SOLID"/>
 <tile id="128" type="SOLID"/>
 <tile id="129" type="SOLID"/>
 <tile id="130" type="SOLID"/>
 <tile id="138" type="SOLID"/>
 <tile id="144" type="SOLID"/>
 <tile id="145" type="SOLID"/>
 <tile id="146" type="SOLID"/>
 <tile id="154" type="SOLID"/>
</tileset>
