<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.4" name="HOTEL" tilewidth="20" tileheight="20" tilecount="160" columns="16">
 <image source="../images/hotel.bmp" width="320" height="200"/>
 <tile id="3" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="5" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="19" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="20" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="21" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="35" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="36" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="37" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="38" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="48" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="50" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="51" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="54" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="64" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="65" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="67" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="80" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="96" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="97" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
 <tile id="98" type="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAGS" value="1"/>
  </properties>
 </tile>
</tileset>
