<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.1" name="HOTEL" tilewidth="20" tileheight="20" tilecount="160" columns="16">
 <image source="../images/hotel.bmp" width="320" height="200"/>
 <tile id="3" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="5" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="19" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="20" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="21" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="35" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="36" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="37" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="38" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="48" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="50" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="51" class="FLAGS"/>
 <tile id="54" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="64" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="65" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="67" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="80" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="82" class="FLAGS"/>
 <tile id="96" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="97" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
 <tile id="98" class="FLAGS">
  <properties>
   <property name="FLAGS" type="int" propertytype="FLAG" value="1"/>
  </properties>
 </tile>
</tileset>
